name: TS Linter

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List repository files
        run: ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # lub inna stabilna wersja

      - name: Install dependencies
        run: npm install

      - name: Run Prettier check
        run: npx prettier --check "**/*.{ts,tsx,js,jsx,json,md}"
